use_frameworks!

platform :ios, '8.0'

target 'JDPopupAnimationView_Example' do
  pod 'JDPopupAnimationView', :path => '../'

  target 'JDPopupAnimationView_Tests' do
    inherit! :search_paths

    
  end
end
